openapi: "3.0.0"
info:
  version: 1.0.0
  title: "@cougargrades/api"
  description: "Public HTTP API for cougargrades.io. <br>See more at: https://github.com/cougargrades/api"
  license:
    name: MIT
servers:
  - url: https://cougargrades.io/api
paths:
  /hello:
    get:
      summary: An example route used for testing
      responses:
        '200':
          description: Reponds with `"world!"`
