name: "Continuous Deployment"
on:
  push:
    branches: ["master","next"]
jobs:
  prep:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}
  buildAndDeploy:
    name: Deploy
    needs: prep
    runs-on: ubuntu-latest
    environment:
      name: Staging
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1
        with:
          working-directory: functions
      - name: Build
        run: npm run build
        working-directory: functions
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: lib
          path: functions/lib
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions,firestore
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
